export const doctorInfo = [
  {
    doctorId: "4005",
    departmentId: "123",
    departmentName: "Cardiologist",
    name: "Mohit",
    dob: "09-02-1999",
    gender: "M",
    phoneNumber: "9828400256",
    email: "mohit@gmail.com",
    state: "Rajasthan",
    district: "Kota",
    subDistrict: "Kota",
    street: "2-D-35 Mahaveer nagar extension",
    pinCode: "324009",
  },
  {
    doctorId: "3006",
    departmentId: "105",
    departmentName: "Dermatologist",
    name: "Vidit",
    dob: "11-07-1998",
    gender: "M",
    phoneNumber: "9828400250",
    email: "vidit@gmail.com",
    state: "Rajasthan",
    district: "Jaipur",
    subDistrict: "Jaipur",
    street: "2-D-35 Malviya nagar extension",
    pinCode: "324009",
  },
  {
    doctorId: "6013",
    departmentId: "103",
    departmentName: "Dentist",
    name: "Shivam",
    dob: "30-11-1990",
    gender: "M",
    phoneNumber: "9226400256",
    email: "shivam@gmail.com",
    state: "Rajasthan",
    district: "Jhalawar",
    subDistrict: "Jhalawar",
    street: "2-D-35 Pratap extension",
    pinCode: "324009",
  },
];
